### ISSUE TITLE
Asteroids of unusual size

### ISSUE THREAD

**Issue by zonkmachine** [impaktor/pioneer#1]
Found this while looking up lots of systems for the sake of testing planet and base names. Rarely an A.O.U.S. (asteroid of unusual size) would pop up. I haven't seen this with any of the other system bodies.  Could be related to density calculations and https://github.com/pioneerspacesim/pioneer/pull/5592 .

master 2c962df832c69c5cd9f4b83e215d7b4916cb2b8f
Iumir (-14, 11, -9)
![asteroid](https://github.com/user-attachments/assets/f7f212a5-8237-4408-90af-fe279b2b85e2)

### Observed behaviour
Asteroid icon can take on a very large size. It seem to also show unrealistic physical values, density for instance.

### Steps to reproduce
Very odd to find a really big one but either manually go through 100's of systems or load the save game below and search for 'iumir).

Ubuntu 22.04
master (2c962df832c69c5cd9f4b83e215d7b4916cb2b8f)

[output.txt](https://github.com/user-attachments/files/16802119/output.txt)
[opengl.txt](https://github.com/user-attachments/files/16802168/opengl.txt)
[asteroidfun.zip](https://github.com/user-attachments/files/16802143/asteroidfun.zip) (not zipped, just renamed)

**Comment by zonkmachine** [comment]
Ooopsie, wrong place... :unicorn: 

Edit: Now here https://github.com/pioneerspacesim/pioneer/issues/5907

**Comment by impaktor** [comment]
@zonkmachine Gräv gärna vidare i mina branches, om du hittar något...

**Comment by zonkmachine** [comment]
OK, det ska bli!
